### ISSUE TITLE
Decoding Error When Sending SMS

### ISSUE THREAD

**Issue by geeksweep** [Andrewangeta/Telesign#7]
Currently I am getting this error everytime i send a SMS but the text still goes through everytime (so far)

@Andrewangeta  - this is what you asked me about in Discord

[ ERROR ] DecodingError.keyNotFound: Value required for key 'status.updated_on'. (Logger+LogError.swift:17)

**Comment by Andrewangeta** [comment]
@geeksweep 
I don't understand how you're getting that error when that value is optional? 
Can you make sure you're using the latest version?

**Comment by geeksweep** [comment]
@Andrewangeta 

I have v. 2.0.0 installed using 

> .package(url: "https://github.com/vapor-community/telesign-provider.git", from: "2.0.0")

it seems to successfully send out a sms though - so I am not sure whats going on

**Comment by Andrewangeta** [comment]
Fixed with version 2.0.1
